version: "2"
services:
  lyra:
    image: elixir:1.4.2-slim
    networks:
      - chord
    volumes:
      - .:/lyra
    working_dir: /lyra
    command: ["mix local.hex --force && mix deps.get "]
    # mix local.rebar --force
    # mix deps.compile proper
    entrypoint: /bin/bash -c
    stdin_open: true
    tty: true
networks:
  chord:
    driver: bridge
